### ISSUE TITLE
does that repo can host non-swag files such as PPT templates?

### ISSUE THREAD

**Issue by jmarcil** [OWASP/owasp-swag#32]
Swag in my definition is something we can print.

So far I think the answer for generic logos is yes, as they can be used to create more swag! Same goes with flyers as they are printable.

But what about PowerPoint templates? icons and web banners? They are definitely made for screen consumption thus not really suited for physical swag?

**Comment by psiinon** [comment]
@jmarcil warning - we may run into size issues if we add too many big files: https://help.github.com/en/articles/what-is-my-disk-quota
We've hit this problem with ZAP and had to change how we were storing things.

**Comment by jmarcil** [comment]
Good point @psiinon. All of the content we have here is to be also shared with the OWASP staff, and unfortunately we can't ask them to go on GitHub for that - it's too difficult to browse for non-developers.

I think what we can do is to put some common assets in the repo for quick access by the community. For the rest, I'll link to Google Drive folders (or whatever makes sense). Currently the Google Drive thing makes sense for the Defcon swag.

**Comment by jmarcil** [comment]
While the last 2 comments are useful, they don't really answer the question of "do we add stuff that isn't printable?". Those files will also be smaller is size so the above concern is less prominent.

**Comment by jmarcil** [comment]
Okay so far this question is moot since I see that some files that have been added are clearly not print quality.

I'll proceed with adding some **logos**, but I'll not put effort on PowerPoint and whatnot since those serve clearly another purpose (example: for speaker to use in conferences).  If you need that, go to https://www.owasp.org/index.php/Marketing/Resources or whatever what page this is in the future.
