### ISSUE TITLE
OWASP Supporter Logos

### ISSUE THREAD

**Issue by jmarcil** [OWASP/owasp-swag#33]
https://www.owasp.org/index.php/Marketing/Resources#tab=IDENTITY

Currently those are marked as 2017.. not super useful. We do have the EPS, but not with the original layers that we can edit text.

We have the choice between either removing the date (don't need the original for that) or generating some from the year to come (would need the original for that).

We could also be clever and regenerate it in SVG and have the date a text that we could update manually.

Either way this needs to be decided by the Foundation itself as I don't have the pay grade for that (I'm a volunteer right ;-).

**Comment by kingthorin** [comment]
According to the new site: https://owasp.org/www-policy/operational/branding a bunch of this is in redevelopment and there's nothing related to 2017 content that I could see.

The 2017 content seems to still be available here &gt; https://wiki.owasp.org/index.php/Marketing/Resources#tab=IDENTITY but I have no idea how long wiki.owasp.org is intended to be available.
