### ISSUE TITLE
Licensing Questions

### ISSUE THREAD

**Issue by bkimminich** [OWASP/owasp-swag#4]
I just pasted my project license (MIT) in along with the logo files. Others might have a CC-BY 4.0 license or Apache 2.0 or BSD. I think most of them allow commercial use, changes and require attribution. Some potential legal issues:

* Having to print attribution on a T-Shirt along with the logo would look kind of silly
* If using a license that allows changes, couldn't someone create or remix our logos into something we might not endorse?
* If commercial use is not restricted, people could sell products with our logos. right? Do we want that?

Big question is, what license can cover all this? I think none of us has trademarked their logos, except for OWASP itself, right?

**Comment by psiinon** [comment]
Good questions.
I think projects should be able to specify their own licenses, as long as they are open source.
As for remixing licenses, thats the whole idea isnt it? But if someone remixes one then it definitely doesnt mean we endorse it.
IANAL of course...

**Comment by bkimminich** [comment]
Me neither.... Well, I think I'll just roll with "Whatever..."... 😜
