### ISSUE TITLE
font used for the letters OWASP

### ISSUE THREAD

**Issue by jaygray0919** [OWASP/owasp-swag#46]
may I ask, did you use a specific font to spell out your letters in the logo?
if so, what font is that?
i am specifically interested in the "W" and would like to reuse it
/jay

**Comment by bkimminich** [comment]
https://github.com/OWASP/owasp-swag/blob/master/owasp/OWASP_Brand_Quick_Reference_Sheet.pdf

This document has all the information on font, color etc.

**Comment by jaygray0919** [comment]
Thank you
