### ISSUE TITLE
add artwork for OWASP project pytm

### ISSUE THREAD

**Issue by jgadsden** [OWASP/owasp-swag#59]
@izar did you want the pytm artwork uploaded to this swag site?

for example https://github.com/izar/pytm/blob/master/docs/pytm-logo.svg

**Comment by izar** [comment]
sorry, don't know how I missed this here!  sure thing, is there anything i need to do for that to happen?

**Comment by kingthorin** [comment]
Just open a PR 😀

**Comment by jgadsden** [comment]
Iput threat dragon under this directory: https://github.com/OWASP/owasp-swag/tree/master/projects

**Comment by bkimminich** [comment]
> Just open a PR 😀
